### ISSUE TITLE
Make routes for games and chatbot

### ISSUE THREAD

**Issue by silkie261001** [ContriHUB/PlayTopia#3]
Create functions/methods regarding route handlers, middlewares, and controllers for chatbot and games: To ensure that when users click on the chatbot or games button, the content opens within the same window without opening a new host or browser tab, you'll need to use some web development techniques.

**Comment by yash037** [comment]
Hey @silkie261001 can you please assign me this issue?

**Comment by sharmavasant** [comment]
@silkie261001 
![Screenshot (2)](https://github.com/ContriHUB/PlayTopia/assets/97390538/3b052eb9-2b94-4545-9415-20b3b7dfcd82)
this error is coming.

**Comment by mangalgithub** [comment]
Is this issue still open and can I work on this issue.

**Comment by mangalgithub** [comment]
Hey @silkie261001 can I work on this as you have assigned this issue from contrihub if it is still open.

**Comment by lokesh-wagh** [comment]
Mam, 
can i convert the chatbot and both of the game's into Component's and then mount them in react

**Comment by silkie261001** [comment]
Yes, you can.

**Comment by lokesh-wagh** [comment]
Hey!! 
@silkie261001  I have made a PR for the issue
Can you review it
