### ISSUE TITLE
Option to react with emojis during livestream.

### ISSUE THREAD

**Issue by silkie261001** [ContriHUB/PlayTopia#7]
Implement a feature to give option to users to react with emojis during a live stream.

**Comment by Sahilgupta3224** [comment]
Hey!
I would like to work on this

**Comment by lokesh-wagh** [comment]
Hey @silkie261001 if the 3 day deadline for hard issue's has been passed can i work on this issue

**Comment by lokesh-wagh** [comment]
Hey @silkie261001 i have been assigned this issue on contrihub can you update that change in github as well

thank you

**Comment by silkie261001** [comment]
ok

**Comment by lokesh-wagh** [comment]
mam there are a lot of bug's in the video call feature

I will try to remove them as well and approach you for any guidance
